# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-18 14:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Belge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=50, verbose_name='Ad')),
                ('aciklama', models.CharField(max_length=50, verbose_name='A\xe7\u0131klama')),
                ('belge', models.FileField(upload_to='documents/')),
                ('aktifmi', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Olu\u015fturma Tarihi')),
                ('duzunleme_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Duzenleme Tarihi')),
            ],
        ),
        migrations.CreateModel(
            name='BelgeDurum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('durum', models.CharField(max_length=20, verbose_name='Durum')),
                ('aktifmi', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Olu\u015fturma Tarihi')),
                ('duzunleme_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Duzenleme Tarihi')),
            ],
        ),
        migrations.CreateModel(
            name='Firma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kutuk_no', models.CharField(max_length=10, verbose_name='K\xfct\xfck Numaras\u0131')),
                ('unvan', models.CharField(max_length=50, verbose_name='\xdcnvan')),
                ('adres', models.CharField(max_length=250, verbose_name='Adres')),
                ('posta_kodu', models.CharField(max_length=10, verbose_name='Posta Kodu')),
                ('sehir', models.CharField(max_length=50, verbose_name='\u015eehir')),
                ('telefon', models.CharField(max_length=20, verbose_name='Telefon')),
                ('faks', models.CharField(max_length=20, verbose_name='Faks')),
                ('eposta', models.CharField(max_length=50, verbose_name='E-Posta')),
                ('aktifmi', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Olu\u015fturma Tarihi')),
                ('duzunleme_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Duzenleme Tarihi')),
            ],
        ),
        migrations.CreateModel(
            name='Is',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanim', models.CharField(max_length=250, verbose_name='Tan\u0131m')),
                ('fatura_no', models.CharField(max_length=20, verbose_name='Fatura Numaras\u0131')),
                ('guvenlik_seviye', models.CharField(max_length=20, verbose_name='G\xfcvenlik Seviyesi')),
                ('is_onay', models.BooleanField(default=False, verbose_name='\u0130\u015f Onay\u0131')),
                ('aktifmi', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Olu\u015fturma Tarihi')),
                ('duzunleme_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Duzenleme Tarihi')),
                ('firma_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safeputapp.Firma', verbose_name='Firma')),
            ],
        ),
        migrations.CreateModel(
            name='Personel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=50, verbose_name='Ad')),
                ('soyad', models.CharField(max_length=50, verbose_name='Soyad')),
                ('adres', models.CharField(max_length=250, verbose_name='Adres')),
                ('telefon', models.CharField(max_length=11, verbose_name='Telefon')),
                ('eposta', models.CharField(max_length=50, verbose_name='E-Posta')),
                ('tcno', models.CharField(max_length=11, verbose_name='TC Kimlik Numaras\u0131')),
                ('ehliyet_no', models.CharField(max_length=20, verbose_name='Ehliyet Numaras\u0131')),
                ('kan_grubu', models.CharField(max_length=10, verbose_name='Kan Grubu')),
                ('sgk_no', models.CharField(max_length=250, verbose_name='SGK Numaras\u0131')),
                ('aktifmi', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Olu\u015fturma Tarihi')),
                ('duzunleme_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Duzenleme Tarihi')),
                ('is_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safeputapp.Is', verbose_name='\u0130\u015f')),
            ],
        ),
        migrations.AddField(
            model_name='belge',
            name='belge_durum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safeputapp.BelgeDurum', verbose_name='Belge Durum'),
        ),
        migrations.AddField(
            model_name='belge',
            name='personel_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safeputapp.Personel', verbose_name='Personel'),
        ),
    ]
