# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-18 14:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('safeputapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=50, verbose_name='Ba\u015fl\u0131k')),
                ('mesaj', models.CharField(max_length=1000, verbose_name='Mesaj')),
                ('baglanti_link', models.CharField(max_length=100, verbose_name='Ba\u011flant\u0131 Linki')),
                ('aktifmi', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Olu\u015fturma Tarihi')),
                ('duzunleme_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Duzenleme Tarihi')),
                ('is_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safeputapp.Is', verbose_name='\u0130\u015f')),
            ],
        ),
    ]
