# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-18 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safeputapp', '0002_eposta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kullanici',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=50, verbose_name='Ad')),
                ('sifre', models.CharField(max_length=50, verbose_name='\u015eifre')),
            ],
        ),
    ]
