# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-18 17:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('safeputapp', '0003_kullanici'),
    ]

    operations = [
        migrations.AddField(
            model_name='belgedurum',
            name='ad',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='Ad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='is',
            name='ad',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='Ad'),
            preserve_default=False,
        ),
    ]
