# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-18 19:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safeputapp', '0005_is_baglanti'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eposta',
            old_name='ad',
            new_name='baslik',
        ),
    ]
