# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-18 23:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('safeputapp', '0006_auto_20190618_2245'),
    ]

    operations = [
        migrations.CreateModel(
            name='IsDurum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanim', models.CharField(max_length=50, verbose_name='Tan\u0131m')),
            ],
        ),
        migrations.RemoveField(
            model_name='is',
            name='is_onay',
        ),
        migrations.AddField(
            model_name='is',
            name='is_durum',
            field=models.ForeignKey(default = 0, on_delete=django.db.models.deletion.CASCADE, to='safeputapp.IsDurum', verbose_name='Durum'),
            preserve_default=False,
        ),
    ]
