# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-19 00:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('safeputapp', '0007_auto_20190619_0248'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuvenlikBelgeTurleri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=50, verbose_name='Ad')),
            ],
        ),
        migrations.CreateModel(
            name='GuvenlikSeviye',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=50, verbose_name='Ad')),
            ],
        ),
        migrations.AddField(
            model_name='guvenlikbelgeturleri',
            name='guvenlik_seviye',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safeputapp.GuvenlikSeviye', verbose_name='G\xfcvenlik Seviyesi'),
        ),
    ]
