# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-30 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safeputapp', '0010_guvenlik'),
    ]

    operations = [
        migrations.AddField(
            model_name='personel',
            name='durum',
            field=models.BooleanField(default=False, verbose_name='Durum'),
        ),
    ]
